const COACHES: Record<string, string> = {
  MEX: "Javier Aguirre",
  RSA: "Hugo Broos",
  KOR: "Hong Myung-bo",
  CZE: "Ivan Hašek",
  CAN: "Jesse Marsch",
  BIH: "Sergej Barbarez",
  QAT: "Bruno Santos",
  SUI: "Murat Yakin",
  BRA: "Dorival Júnior",
  MAR: "Walid Regragui",
  HAI: "Sébastien Migné",
  SCO: "Steve Clarke",
  USA: "Mauricio Pochettino",
  PAR: "Gustavo Alfaro",
  AUS: "Tony Popovic",
  TUR: "Vincenzo Montella",
  GER: "Julian Nagelsmann",
  CUW: "Dick Advocaat",
  CIV: "Emerse Faé",
  ECU: "Sebastián Beccacece",
  NED: "Ronald Koeman",
  JPN: "Hajime Moriyasu",
  TUN: "Samuel Zauber",
  SWE: "Jon Dahl Tomasson",
  BEL: "Domenico Tedesco",
  EGY: "Hossam Hassan",
  IRN: "Amir Ghalenoei",
  NZL: "Darije Kalezić",
  ESP: "Luis de la Fuente",
  CPV: "Bubista",
  KSA: "Hervé Renard",
  URU: "Marcelo Bielsa",
  FRA: "Didier Deschamps",
  SEN: "Aliou Cissé",
  IRQ: "Jesús Casas",
  NOR: "Ståle Solbakken",
  ARG: "Lionel Scaloni",
  ALG: "Djamel Belmadi",
  AUT: "Ralf Rangnick",
  JOR: "Jürgen Klinsmann",
  POR: "Roberto Martínez",
  COD: "Sébastien Desabre",
  UZB: "Srečko Katanec",
  COL: "Néstor Lorenzo",
  ENG: "Thomas Tuchel",
  CRO: "Zlatko Dalić",
  GHA: "Otto Addo",
  PAN: "Thomas Christiansen",
};

export function getCoach(teamCode: string): string {
  return COACHES[teamCode.toUpperCase()] ?? "TBD";
}
